### ISSUE TITLE
having issues with initial test 

### ISSUE THREAD

**Issue by Tom-a-Hawk** [pydata/parallel-tutorial#25]
I am trying to make sure I have everything up and running before the Strata Conference next week! 

Running Windows 10 Education, version 1703, 64-bit
Using Git Bash

Followed the install instructions for the parallel-tutorial
When I attempt to test the installation, I get an error.

Operator error? 
<img width="725" alt="initial_test" src="https://user-images.githubusercontent.com/22554083/30674275-05103424-9e47-11e7-9410-d074c786f6c5.PNG">

**Comment by mrocklin** [comment]
My guess is something was lost while copy-pasting or transcribing.  Perhaps
a non-traditional quote mark or non-breaking space?

**Comment by mrocklin** [comment]
We'll also be refreshing things in the next few days, so you may want to
redo these operations early next week.

**Comment by Tom-a-Hawk** [comment]
Switched out ' with ". This got rid of the syntax error .... but the command didn't appear to actually do anything. 
<img width="774" alt="initial_test2" src="https://user-images.githubusercontent.com/22554083/30675562-3e426eee-9e4f-11e7-8d72-0ef01ca788f3.PNG">

I'll wait till after the refresh and redo everything like you suggested. 
Thanks for getting back to me so quickly!

**Comment by Gandhi-uses-nukes** [comment]
Hi, I had the same issue under Win10.
You get the error because Windows only like double quotes (Python understands both types, single- and double quotes as long as you use them in pairs)

Your second try worked because you only told python to import these packages. Everything worked fine and you get nothing back (Nothing back = good). This is only a check to see if the packages are correctly installed on your system.

**Comment by Tom-a-Hawk** [comment]
thanks for the help!!!

**Comment by mrocklin** [comment]
I've changed the readme to have double quotes
